acme_bundle_stare_store:
    resource: "@AcmeBundleStareStoreBundle/Controller/"
    type:     annotation
    prefix:   /

acme_bundle_blog:
    resource: "@AcmeBundleBlogBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

index:
    path: /index
    defaults: {_controller: AcmeBundleStareStoreBundle:Index:index}

show-register-user:
    path: /register-user
    defaults: {_controller: AcmeBundleStareStoreBundle:Register:showUser}

show-register-owner:
    path: /register-owner
    defaults: {_controller: AcmeBundleStareStoreBundle:Register:showOwner}

register-user:
    path: /register/user
    defaults: {_controller: AcmeBundleStareStoreBundle:Register:user}

register-owner:
    path: /register/owner
    defaults: {_controller: AcmeBundleStareStoreBundle:Register:owner}

login:
    path: /login
    defaults: {_controller: AcmeBundleStareStoreBundle:Register:showlogin}

login-user:
    path: /login/user
    defaults: {_controller: AcmeBundleStareStoreBundle:Register:login}
