acme_bundle_stare_store:
    resource: "@AcmeBundleStareStoreBundle/Controller/"
    type:     annotation
    prefix:   /

acme_bundle_blog:
    resource: "@AcmeBundleBlogBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation


index:
    path: /index
    defaults: {_controller: AcmeBundleStareStoreBundle:Index:index}

index2:
    path: /index2
    defaults: {_controller: AcmeBundleStareStoreBundle:Index:index2}

login:
    path: /login
    defaults: {_controller: AcmeBundleStareStoreBundle:Register:showlogin}

login-user:
    path: /login/user
    defaults: {_controller: AcmeBundleStareStoreBundle:Register:login}

logout:
    path: /logout
    defaults: {_controller: AcmeBundleStareStoreBundle:Register:logout}



show-register-owner:
    path: /register-owner
    defaults: {_controller: AcmeBundleStareStoreBundle:Register:showOwner}

show-register-store:
    path: /register-store
    defaults: {_controller: AcmeBundleStareStoreBundle:Register:showStore}

register-owner:
    path: /register/owner
    defaults: {_controller: AcmeBundleStareStoreBundle:Register:owner}

register-store:
    path: /register/store
    defaults: {_controller: AcmeBundleStareStoreBundle:Register:store}



show-register-product:
    path: /register-product
    defaults: {_controller: AcmeBundleStareStoreBundle:Register:showProduct}

register-product:
    path: /register/product
    defaults: {_controller: AcmeBundleStareStoreBundle:Register:product}



show-register-user:
    path: /register-user
    defaults: {_controller: AcmeBundleStareStoreBundle:Register:showUser}

register-user:
    path: /register/user
    defaults: {_controller: AcmeBundleStareStoreBundle:Register:user}

show-store:
    path: /store/{id}
    defaults: {_controller: AcmeBundleStareStoreBundle:Store:showMain}

show-category:
    path: /category/{id}
    defaults: {_controller: AcmeBundleStareStoreBundle:Store:showCategory}

show-product:
    path: /product/{id}
    defaults: {_controller: AcmeBundleStareStoreBundle:Store:showProduct}

mail:
    path: /mail
    defaults: {_controller: AcmeBundleStareStoreBundle:Default:mail}

add-to-cart:
    path: /add-cart
    defaults: {_controller: AcmeBundleStareStoreBundle:Shop:addCart}

show-cart:
    path: /cart
    defaults: {_controller: AcmeBundleStareStoreBundle:Shop:showCart}

shop:
    path: /shop
    defaults: {_controller: AcmeBundleStareStoreBundle:Shop:shop}

button-cart:
    path: /button-cart
    defaults: {_controller: AcmeBundleStareStoreBundle:Shop:buttonCart}